#:schema node_modules/wrangler/config-schema.json
name = "yaibot"
main = "src/index.ts"
compatibility_date = "2025-11-17"
minify = true
upload_source_maps = true
workers_dev = false

[observability]
enabled = true
traces.enabled = true

[[d1_databases]]
binding = "DB"
database_id = "02a7b5de-cc73-48bc-8803-24d245bff001"
database_name = "inlinedb"

[vars.BOT_INFO]
id = 7969353410
is_bot = true
first_name = "Neko Inline Bot"
username = "NekoInlineBot"
can_join_groups = true
can_read_all_group_messages = false
supports_inline_queries = true
can_connect_to_business = false
has_main_web_app = false
